//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptanceCriteria
    {
        public int ID { get; set; }
        public Nullable<long> MemberId { get; set; }
        public string SonsAproval { get; set; }
        public string DaughtersAproval { get; set; }
        public string AuntsAproval { get; set; }
        public string UnclesAproval { get; set; }
        public string SisterAproval { get; set; }
        public string BrothersAproval { get; set; }
        public string MotherAproval { get; set; }
        public string FathersAproval { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
