//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatHistoryDeletedMember
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public long MessageId { get; set; }
        public Nullable<System.DateTime> HistoryDeletedDatetime { get; set; }
    }
}
