//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatFriendRequest
    {
        public long Id { get; set; }
        public long FromId { get; set; }
        public long ToId { get; set; }
        public string RequestStatus { get; set; }
        public bool IsBlocked { get; set; }
        public Nullable<long> BlockedBy { get; set; }
        public Nullable<System.DateTime> RequestDatetime { get; set; }
    }
}
