//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public long CountryID { get; set; }
        public string CountryName { get; set; }
        public string ISO3 { get; set; }
        public string ISO { get; set; }
        public string NameCode { get; set; }
        public string PhoneCode { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string FlagIcon { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreadtedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
