//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivorcePolicy
    {
        public long ID { get; set; }
        public Nullable<long> MemberId { get; set; }
        public string dropdownOption { get; set; }
        public string Amountcheckbox { get; set; }
        public Nullable<int> AmountFrom { get; set; }
        public Nullable<int> AmountTo { get; set; }
        public string IncomeCurrency { get; set; }
        public string HouseCheckBox { get; set; }
        public string HouseDetail { get; set; }
        public string MiscellaneousCheckbox { get; set; }
        public string MiscellaneousDetail { get; set; }
        public Nullable<bool> ThreeDivorcePolicy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
