//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilitiesResultFemale
    {
        public long ID { get; set; }
        public Nullable<long> MemberId { get; set; }
        public Nullable<long> FacilityId { get; set; }
        public Nullable<bool> One { get; set; }
        public Nullable<bool> Two { get; set; }
        public Nullable<bool> Three { get; set; }
        public Nullable<bool> Four { get; set; }
        public string FacilityFor { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
