//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRegistration
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string ProfileCreatedBy { get; set; }
        public string MotherTongue { get; set; }
        public string NoOfMarriage { get; set; }
        public string LookingFor { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<long> MaritalStatus { get; set; }
        public string NoOfChildren { get; set; }
        public string Subcast { get; set; }
        public string ProfilePicPath { get; set; }
        public Nullable<long> ReligionId { get; set; }
        public Nullable<long> SectId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string AboutMe { get; set; }
        public Nullable<long> UserRole { get; set; }
        public Nullable<bool> IsMobilePic { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
