//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLoginDetail
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsEmailConfirmed { get; set; }
        public string ConfirmationCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsFirstLoginAttempt { get; set; }
        public bool IsMobileUser { get; set; }
        public string FirebaseUserId { get; set; }
    }
}
