//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFamilyDetail
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public string ParentContactNo { get; set; }
        public Nullable<long> FamilyValue { get; set; }
        public Nullable<long> FamilyType { get; set; }
        public Nullable<long> FamilyStatus { get; set; }
        public bool IsMotherAlive { get; set; }
        public bool IsFatherAlive { get; set; }
        public string FatherOccupation { get; set; }
        public string NoOfBrothers { get; set; }
        public string NoOfSisters { get; set; }
        public string FamilyDetail { get; set; }
    }
}
