//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPackagePayment
    {
        public long Id { get; set; }
        public long MemberPackageSubscriptionId { get; set; }
        public string TransactionId { get; set; }
        public string PayerId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Status { get; set; }
        public string PaymentType { get; set; }
        public Nullable<long> PaymentOptionId { get; set; }
    }
}
