//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLocationDetail
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public Nullable<int> CountryLivingIn { get; set; }
        public string PlaceOfBirth { get; set; }
        public string ResidingState { get; set; }
        public string ResidingCity { get; set; }
        public Nullable<int> Citizenship { get; set; }
    }
}
