//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public long Id { get; set; }
        public Nullable<int> PackageTypeId { get; set; }
        public bool CanMemberViewMobileNo { get; set; }
        public Nullable<int> NumberOfMobileNo { get; set; }
        public int NumberOfChatMessages { get; set; }
        public bool CanViewPhoto { get; set; }
        public bool IsVisibleHighProfile { get; set; }
        public bool CanChat { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
