//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marryme.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WifeDetailResult
    {
        public long ID { get; set; }
        public Nullable<long> MemberId { get; set; }
        public Nullable<byte> ExsitingWife { get; set; }
        public string WifeReligion { get; set; }
        public string MarriageYear { get; set; }
        public string WifeLocation { get; set; }
        public string WifeKids { get; set; }
        public string WifeJob { get; set; }
        public string LivingStatus { get; set; }
        public Nullable<byte> EducationLevelId { get; set; }
        public string HaveWife { get; set; }
        public string WifeAge { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
